"""Turn the per-slice notes into a worklist that cannot go stale.

The readme's Notes column mixed facts about documents with gaps in our parsing,
and read as background noise either way. Split by status it becomes three
lists: what is settled, what is open, and what nobody has established.

Everything here is detected from the rows. A line cannot be marked done while
the condition still holds, and it disappears by itself once the condition stops
holding - fix Jharkhand's image-only seat column and the entry goes on the next
`make worklist`.

Writes data/worklist.csv and WORKLIST.md.
"""

import argparse
import collections
import csv
import sys

from local_reservations.common import datasets, slice_checks
from local_reservations.common import notes as notes_module
from local_reservations.common.runlog import command
from local_reservations.paths import ROOT

WORKLIST_CSV = ROOT / "data" / "worklist.csv"
WORKLIST_MD = ROOT / "WORKLIST.md"
README = ROOT / "readme.md"

START, END = "<!-- worklist:start -->", "<!-- worklist:end -->"

COLUMNS = [
    "status",
    "note_id",
    "state",
    "year",
    "tier",
    "rows_affected",
    "share",
    "text",
    "detail",
    "because",
    "closes_with",
]

ORDER = [
    notes_module.OPEN_GAP,
    notes_module.BLOCKED,
    notes_module.PARKED,
    notes_module.UNDETERMINED,
    notes_module.SOURCE_PROPERTY,
]


def gather():
    grouped = collections.defaultdict(list)
    for _, rows in datasets.pooled():
        for row in rows:
            grouped[
                (row.get("state", ""), row.get("year", ""), row.get("tier", ""))
            ].append(row)

    out = []
    for (state, year, tier), rows in sorted(grouped.items()):
        a_slice = slice_checks.Slice(state, year, tier, rows, ROOT)
        for note in notes_module.for_slice(a_slice):
            out.append(
                dict(
                    note,
                    state=state,
                    year=year,
                    tier=tier,
                    share=round(note["rows_affected"] / max(len(rows), 1), 4),
                )
            )
    return out


SECTIONS = {
    notes_module.OPEN_GAP: (
        "Open gaps",
        "The document holds more than our parse recovered. Each line says what "
        "would close it. Sorted by rows affected.",
    ),
    notes_module.BLOCKED: (
        "Blocked",
        "Closable, but not from here. These are not waiting on effort; they "
        "are waiting on access, and keeping them apart from the open gaps is "
        "what stops the open list from looking permanently hopeless.",
    ),
    notes_module.PARKED: (
        "Parked",
        "Closable from here, and deliberately not being closed. These are real "
        "and the lines below say what is still wrong; the decision is that the "
        "effort is better spent elsewhere for now. Written down so the same "
        "state is not re-triaged by everyone who reads the list, and so that "
        '"still open" is not mistaken for "nobody noticed".',
    ),
    notes_module.UNDETERMINED: (
        "Undetermined",
        "We have not established whether these are properties of the sources or "
        "gaps in our collecting. That question is itself the work - asserting "
        '"no results document exists" is a claim about everything a state '
        "published, not about the file in hand.",
    ),
    notes_module.SOURCE_PROPERTY: (
        "Accepted properties of the sources",
        "The document says what it says. Nothing to do, but a reader needs to "
        "know before using the numbers.",
    ),
}


def render(entries):
    out = [
        "# Worklist",
        "",
        "*Generated by `make worklist`. Every line is detected from the "
        "parsed rows, so nothing here can be marked done while it is still "
        "true, or linger once it is fixed.*",
        "",
    ]
    for status in ORDER:
        subset = sorted(
            [e for e in entries if e["status"] == status],
            key=lambda e: -e["rows_affected"],
        )
        title, blurb = SECTIONS[status]
        out += [f"## {title} ({len(subset)})", "", blurb, ""]
        if not subset:
            out += ["Nothing.", ""]
            continue
        out += [
            "| Rows | State | Year | Tier | What | Detail |",
            "|---|---|---|---|---|---|",
        ]
        for e in subset:
            out.append(
                f"| {e['rows_affected']:,} | {e['state']} | {e['year']} "
                f"| `{e['tier']}` | {e['text']} | {e['detail'] or '—'} |"
            )
        out.append("")
        # the reasoning belongs once per note, not once per slice
        seen = []
        for e in subset:
            if e["note_id"] in seen:
                continue
            seen.append(e["note_id"])
            out.append(f"**{e['text']}** — {e['because']}")
            if e["closes_with"]:
                out.append(f"  *Closes with:* {e['closes_with']}.")
            out.append("")
    return "\n".join(out) + "\n"


def summary_block(entries):
    tally = collections.Counter(e["status"] for e in entries)
    rows = collections.Counter()
    for e in entries:
        rows[e["status"]] += e["rows_affected"]
    lines = ["| | Entries | Rows affected |", "|---|---|---|"]
    for status in ORDER:
        title = SECTIONS[status][0]
        lines.append(f"| [{title}](WORKLIST.md) | {tally[status]} | {rows[status]:,} |")
    return "\n".join(lines)


@command("document", artifact="worklist")
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated files differ from what is on disk",
    )
    args = ap.parse_args()

    entries = gather()
    text = render(entries)

    stale = []
    if args.check:
        if not WORKLIST_MD.exists() or WORKLIST_MD.read_text(encoding="utf-8") != text:
            stale.append(WORKLIST_MD.name)
    else:
        WORKLIST_CSV.parent.mkdir(parents=True, exist_ok=True)
        with WORKLIST_CSV.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(
                fh, fieldnames=COLUMNS, extrasaction="ignore", lineterminator="\n"
            )
            writer.writeheader()
            writer.writerows(
                sorted(
                    entries,
                    key=lambda e: (ORDER.index(e["status"]), -e["rows_affected"]),
                )
            )
        WORKLIST_MD.write_text(text, encoding="utf-8")

        readme = README.read_text(encoding="utf-8")
        block = f"{START}\n\n{summary_block(entries)}\n\n{END}"
        if START in readme and END in readme:
            head, rest = readme.split(START, 1)
            README.write_text(head + block + rest.split(END, 1)[1], encoding="utf-8")

    tally = collections.Counter(e["status"] for e in entries)
    print(f"\n{len(entries)} worklist entries -> {WORKLIST_MD.name}")
    print("  " + "  ".join(f"{k}={v}" for k, v in tally.most_common()))
    if stale:
        print(f"  out of date: {stale}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
